### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by corranwebster** [celiagg/celiagg#29]
Trying to install master from source on OS X gives the following error:
```
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    packages=['celiagg', 'celiagg.tests']
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 51, in configuration
    config.add_subpackage('celiagg')
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
    caller_level = 2)
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
    caller_level = caller_level + 1)
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "celiagg/setup.py", line 140, in configuration
    cflags, ldflags = get_freetype_info()
  File "celiagg/setup.py", line 73, in get_freetype_info
    data = collect_data()
  File "celiagg/setup.py", line 68, in collect_data
    data[key] = run_cmd(cmd_prefix + args, env=env)
  File "celiagg/setup.py", line 58, in run_cmd
    env=env, stderr=dev_null.fileno())
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/cwebster/.edm/envs/celiagg/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by corranwebster** [comment]
Proximate cause is the lack of `pkg-config` on a default OS X install.

**Comment by corranwebster** [comment]
And with `pkg-config` installed via homebrew, it seems to compile correctly.  Probably should have build instructions that list out the requirements for OS X.  It looks like the requirements are no worse than matplotlib's so I can live with this.

**Comment by jwiggins** [comment]
Wow... That error message is basically useless.
